### ISSUE TITLE
Running Ezpc with 64bit numbers, gives malloc(): memory corruption Aborted (core dumped)

### ISSUE THREAD

**Issue by auxillary1902** [mpc-msri/EzPC#36]
Hello,
I am trying to run a 64 bit ezpc program to find input 'a' raised to exponent 'b' Mod 998244353 where 'b' is also input. I wrote a **fast exponentiation algorithm** to do so similar to [.This algorithm in Geeksforgeeks](https://www.geeksforgeeks.org/modular-exponentiation-power-in-modular-arithmetic/) But i need modular exponentiation, so I incorporated the library function **unsignedmodbl(uint64_bl x, uint64_bl y)** which uses the function **longDivision(uint64_bl x, uint64_bl y, bool_pl getQuotient)** which is defined in **EZPC/library/Library64.ezpc** to take mod operation , I am able to compile the program ,but on running the client/server, it gives me the following error:
![code](https://user-images.githubusercontent.com/28973485/77847654-65082d80-71dc-11ea-8655-723353ea3e10.png)

**Comment by nishkum** [comment]
Hi! Would it be possible for you to share the ezpc program you wrote?

**Comment by auxillary1902** [comment]
Thank You for your fast reply,

The following is the code for the exponentiation algorithm I have written in ezpc:
Without the **modulo 998244353**, just simple exponentiation works for numbers like 3 raised to 9 but returns a value 0 when supplying large numbers(like say 7 raised to 150), maybe due to overflow of the data type. I have used the library function in the defined EZPC library. I copied those functions and pasted it above main so that my code can use those functions.
![code2](https://user-images.githubusercontent.com/28973485/77848200-dcd85700-71e0-11ea-89f0-b5c5f9b4d6b1.png)

**Comment by nishkum** [comment]
I haven't run the said program myself, but could you try these things:
- Try compiling and running against the cleartext CPP backend of ezpc. This can be done by using the 
option codegen=CPP instead of codegen=ABY while compiling the ezpc program.
- If CPP works, then this can be an issue with using ABY. For eg, right now we are setting upper bound on the memory to allocate for the gates at the beginning by using a heuristic number. Check this issue: https://github.com/mpc-msri/EzPC/issues/9 -- try varying the number of gates and checking if you still get a seg fault or bad_alloc. 
- If CPP itself doesn't work, then it can be some other problem. Debug the cleartext cpp code (it will be just plain c++ -- so should be easy and doable).

My guess is the problem is the 2nd one i mentioned -- just varying the #gates on a large enough machine should do the trick.

**Comment by auxillary1902** [comment]
Thank You so much for the reply.
You were right , the problem seems to be with ABY. I generated the cleartext CPP using the codegen option and built executable and ran it and it perfectly prints exponentiation modulo 998244353. This executable is fine for my project.



With respect to #9 , when we cloned the repo and set it up, we had the same issue (getting bad_alloc)which we resolved by changing the number of gates from 520000000 to a lesser value like 52000 and managed to make our **simple exponentiation** work. Now when I ran this modular exponentiation code, it still gave me this **memory corruption error upto 52000000 gates**, when I **add one more zero, it reverts back to bad_alloc error.** . So I dont think it is the number of gates causing the **memory corruption** but something to do with how  the memory allocation is done in the ABY generated .cpp file from the lex file ,**maybe like has dangling pointers** or trying to **access a different portion of the memory stack** which the program does not have access to.

When this memory corruption error arised, I ran the compiled ,built executable through **GDB** debugger to see which part of the code I am getting this error. It gave me this output:
![code3](https://user-images.githubusercontent.com/28973485/77852276-6563f100-71fb-11ea-91d0-decfb27dc03e.png)

It says the error maybe in function **longDivision()** . This function is called from **unsignedmodbl.** So there maybe an error in the longDivision method defined in the library for 64bit. The same method works perfectly for 32bit. 

I kindly request you to check this if possible and keep this issue open if you feel it needs work. 
Thank You

**Comment by nishkum** [comment]
I think the issue is the #gates. With unsigned long division in 64 bits, my guess is the number of gates is too large for the malloc to work. The stack trace you printed clearly shows that malloc call failed. The thing is the memory is allocated at runtime by the program and in this case the memory is just too large and so the call fails. If you run it on a larger machine, you shouldn't see the issue (try it if you do have access to such a machine -- though I don't know how large a machine suffices).

ABY circuits can quickly grow huge. Which is why the problem. This is not the first time we are seeing this. In fact, if you check the EzPC paper, we have a portioning algorithm which checkpoints state and allows large circuits to execute. I haven't used that part of the code in a while and I am not sure if it works correctly though.

If you really need this, consider the alternative of using Porthos -- its a 3 PC framework and not 2 PC like ABY and it will be very light and quick. Check the paper or the main readme of this repo for more info.

**Comment by auxillary1902** [comment]
Cool, will look at the portioning algorithm. Thanks for the reply! Also by 'larger machine' , do you mean a machine with more RAM?

**Comment by nishkum** [comment]
Yes

**Comment by L-coder148** [comment]
Hello, it seems that you ran the  [ABY](https://github.com/encryptogroup/ABY) . I have been learning the library ABY recently, but I can not find the example modular exponentiation implemented in ABY, I have tried to implement it, but it occurs the problem `Segmentation fault (core dumped)`.@auxillary1902
