### ISSUE TITLE
what():  std::bad_alloc when running EzPC docker

### ISSUE THREAD

**Issue by TianshuoCong** [mpc-msri/EzPC#59]
Hello!
After Installation of the docker, I followed issue#15 and issue#9, but it doesn't work for me.
I have modified the number to be smaller in
`party = new ABYParty(role, address, port, seclvl, bitlen, nthreads, mt_alg, 520000000);`

Here are the attached pics..
![1](https://user-images.githubusercontent.com/21216238/84326651-097cf780-abb0-11ea-936a-a9f98ad5de19.PNG)
![2](https://user-images.githubusercontent.com/21216238/84326658-0eda4200-abb0-11ea-94b3-13b43671dc6b.PNG)
![3](https://user-images.githubusercontent.com/21216238/84326663-11d53280-abb0-11ea-9907-ca158669de25.PNG)

Thx!

**Comment by mayank0403** [comment]
Hi,

Can you please check the memory allocated to your Docker container?
Maybe that memory is low. You can increase it and give it a try.
If the issue persists, then let us know here.

Thanks,
Mayank.

**Comment by TianshuoCong** [comment]
Hello!
Thanks for your reply!

I tried to check the MEM limits, and run
`sudo docker run -m 4g --network host --privileged -it ezpc_image`
and also reduce 520000000 to be smaller,
but still doesn't work..

So I'm confused and ask u for help again.

![4](https://user-images.githubusercontent.com/21216238/84380610-349c3100-ac1a-11ea-94d4-533ffc18327c.PNG)


Thanks,
Tianshuo.

**Comment by mayank0403** [comment]
Can you run the cpp executable (mentioned in ./run_docker_server.sh) with gdb and send across the backtrace log?
Please make sure to change the CMake inside ABY directory in your Docker container to run in Debug mode and then recompile the project.

**Comment by TianshuoCong** [comment]
Up to now, I still can't solve it...
Could you show me the detail instructions step by step?
Thank you for your patience and help!

**Comment by mayank0403** [comment]
I have updated the `Dockerfile` and related scripts in the `master` branch. Please try that once. You don't need to use the `Dockerfile` from `random_forest` branch anymore.

Here is the step by step process that I followed: (you will need two terminal windows which I refer to as `Terminal 1` and `Terminal 2` below)
On `Terminal 1`
```
git clone https://github.com/mpc-msri/EzPC
cd EzPC/EzPC/Docker/
sudo docker build --no-cache -t ezpc_image .
sudo docker run --network host --privileged -it ezpc_image /bin/bash
cd Docker
./compile_docker_example.sh ** The script will ask for which test to build. Input 0 or 1 depending on that. **
```
On `Terminal 2`
```
sudo docker container ls
sudo docker exec -it CONTAINER_ID /bin/bash ** Here CONTAINER_ID is the ID listed in the output of sudo docker container ls.**
cd Docker
```
On `Terminal 1`
```
./run_docker_example_server.sh
```
On `Terminal 2`:
```
./run_docker_example_client.sh
```
This works for me. I don't get any issues with this. When I run `free` inside the docker container, I see 2GB RAM, so that is all you need to run the examples included with this repo. I didn't change the number of AND gates required and have left everything to default.

**Comment by mayank0403** [comment]
Closing this issue because the above steps work fine. If you still face any issues, feel free to open the issue.
